### ISSUE TITLE
Server error: 401

### ISSUE THREAD

**Issue by pax** [Planetary-Computers/autotab-starter#11]
I've just installed it - disabled record_mode (as per [here](https://github.com/Planetary-Computers/autotab-starter/issues/1#issuecomment-1773569275)). 

Any action I do, seemingly regardless the url, results in _Server error: 401_ in the sidebar. 
Is there any way I should debug further?

LE: console gives me:
`../autotab-starter/src/record.py(27)record()->None`

**Comment by jonasalexander** [comment]
Hi, thanks for trying out autotab! Sorry if the other comment was unclear - you will still need to log in to autotab in order to use it (we need this to prevent our Open AI credits being drained). The change I mentioned in that comment was that you no longer have to put your Google credentials in a file in the autotab-starter repo. Instead, you can just sign in to autotab with Google the way you would any other 3rd party application that uses Google auth.

I'm working on a feature that let's you get an autotab API key and use that to log in, will likely have that ready later today! Hope this helps.

**Comment by jonasalexander** [comment]
You can now go to https://www.autotab.com/dashboard, get your API key and then just set the autotab_api_key in your .autotab.yaml file locally! No more Google credentials within 100 feet of autotab. :)

**Comment by jonasalexander** [comment]
You can now go to https://www.autotab.com/dashboard, get your API key and then just set the autotab_api_key in your .autotab.yaml file locally! No more Google credentials within 100 feet of autotab. :)
