### ISSUE TITLE
Failing to authenticate on "Couldn't sign you in".

### ISSUE THREAD

**Issue by smomen** [Planetary-Computers/autotab-starter#12]
Hi - I've followed the docs, and after running `autotab record` on Mac I get the following. 
<img width="675" alt="image" src="https://github.com/Planetary-Computers/autotab-starter/assets/5103172/c1bfb823-2d0e-428c-a053-9e7f7dedaa83">

- I've tried both adding creds in the yaml and omitting them. No change.
- Javascript is enabled.

Am I missing something?

**Comment by jonasalexander** [comment]
Hi, this was because we were tripping up Google's detection of chromedriver/Selenium which prevents logins with `@gmail.com` addresses (but not Google workspace emails which is why we didn't catch it). We've just merged a change that should fix this, please try out the most recent version on `main`!

**Comment by smomen** [comment]
Thanks @jonasalexander - confirming it's working now, thanks for the merge!
